#!/bin/sh
set -eu

prototype_directory=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
target_file="$prototype_directory/ios/Keyboard/Resources/english-glide-frequency.txt"
checksum_file="$target_file.sha256"
notice_directory="$prototype_directory/ios/Keyboard/Resources/GlideLexiconNotices"
temporary_directory=$(mktemp -d /tmp/hex-glide-lexicon.XXXXXX)
source_file="$temporary_directory/frequency_dictionary_en_82_765.txt"
filtered_file="$temporary_directory/filtered.txt"
sorted_file="$temporary_directory/sorted.txt"

trap 'rm -rf "$temporary_directory"' EXIT HUP INT TERM

source_revision=c239062ae02961df18ab7da1671d01b4388204e0
source_url="https://raw.githubusercontent.com/wolfgarbe/SymSpell/$source_revision/SymSpell/frequency_dictionary_en_82_765.txt"
source_checksum=c604e1121e398ae7c7fbf777f11e0a0f2fa66eda932cb9fba1321466cf3acd7b

curl --fail --location --silent --show-error "$source_url" --output "$source_file"
actual_source_checksum=$(shasum -a 256 "$source_file" | awk '{ print $1 }')
test "$actual_source_checksum" = "$source_checksum"

LC_ALL=C perl -i -pe 's/^\xEF\xBB\xBF//' "$source_file"

LC_ALL=C awk '
    $1 ~ /^[a-z]+$/ && $2 ~ /^[1-9][0-9]*$/ && !seen[$1]++ {
        print $1, $2
    }
' "$source_file" > "$filtered_file"

LC_ALL=C sort -k2,2nr -k1,1 "$filtered_file" > "$sorted_file"

{
    printf '%s\n' \
        '# PROTOTYPE: generated by generate-glide-lexicon.sh' \
        '# SymSpell revision c239062ae02961df18ab7da1671d01b4388204e0' \
        '# Top 20,000 unique lowercase ASCII entries, frequency then lexical order'
    sed -n '1,20000p' "$sorted_file"
} > "$target_file"

generated_count=$(awk '!/^#/ { count += 1 } END { print count }' "$target_file")
test "$generated_count" = 20000
generated_checksum=$(shasum -a 256 "$target_file" | awk '{ print $1 }')
printf '%s  %s\n' "$generated_checksum" "$(basename -- "$target_file")" > "$checksum_file"

mkdir -p "$notice_directory"
curl --fail --location --silent --show-error \
    "https://raw.githubusercontent.com/wolfgarbe/SymSpell/$source_revision/LICENSE" \
    --output "$notice_directory/SymSpell-MIT.txt"
curl --fail --location --silent --show-error \
    "https://raw.githubusercontent.com/en-wl/wordlist/v1/scowl/Copyright" \
    --output "$notice_directory/SCOWL-v1-Copyright.txt"
curl --fail --location --silent --show-error \
    "https://creativecommons.org/licenses/by/3.0/legalcode.txt" \
    --output "$notice_directory/CC-BY-3.0.txt"

printf 'Generated %s entries at %s\n' \
    "$generated_count" \
    "$target_file"
